#!/usr/bin/env python3
"""Generate the M²NDP instruction tests.

One test per instruction, checked in target code against values computed
here. Writing 64 of these by hand would mean 64 chances to compute the
expected answer the same wrong way the simulator does; deriving them from
Python's own arithmetic keeps the oracle independent of the implementation.

Each test runs the instruction over four lanes and compares memory against
the expected result, accumulating a difference that must come out zero. Two
lanes are given the same index on purpose: an indexed atomic has to apply
both, which is exactly what a broken one gets wrong.

    ./sim/gen-tests.py > sim/generated-tests.s
"""

import struct
import sys

# (mnemonic suffix, python op on the old/operand pair)
INT_OPS = [
    ("vamoadd",   lambda o, v, b: (o + v) & ((1 << b) - 1)),
    ("vamoswap",  lambda o, v, b: v),
    ("vamoxor",   lambda o, v, b: o ^ v),
    ("vamoand",   lambda o, v, b: o & v),
    ("vamoor",    lambda o, v, b: o | v),
    ("vamomin",   lambda o, v, b: min(sext(o, b), sext(v, b)) & ((1 << b) - 1)),
    ("vamomax",   lambda o, v, b: max(sext(o, b), sext(v, b)) & ((1 << b) - 1)),
    ("vamominu",  lambda o, v, b: min(o, v)),
    ("vamomaxu",  lambda o, v, b: max(o, v)),
]

FP_OPS = [
    ("vfamoadd",  lambda o, v: o + v),
    ("vfamoswap", lambda o, v: v),
    ("vfamomin",  lambda o, v: min(o, v)),
    ("vfamomax",  lambda o, v: max(o, v)),
]

SCALAR_OPS = [
    ("famoadd",   lambda o, v: o + v),
    ("famoswap",  lambda o, v: v),
    ("famomin",   lambda o, v: min(o, v)),
    ("famomax",   lambda o, v: max(o, v)),
]

IDX_WIDTHS = [8, 16, 32, 64]

# VLEN is 128, so an element width of 64 fits only two elements per register
# at LMUL 1 and vsetivli would quietly clamp vl to 2. Pick the LMUL that holds
# all four lanes instead.
VLEN = 128
LANES = 4


def lmul_for(width):
    return 1 if VLEN // width >= LANES else 2


# Data lives in v8, indices in v16: far enough apart that neither register
# group runs into the other at LMUL 2.
VD, VIDX = 8, 16


def sext(x, bits):
    return x - (1 << bits) if x >> (bits - 1) else x


def f32_bits(x):
    return struct.unpack("<I", struct.pack("<f", x))[0]


def f64_bits(x):
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def f16_bits(x):
    return struct.unpack("<H", struct.pack("<e", x))[0]


out = []
def emit(s=""):
    out.append(s)


def record(n):
    """Remember the first test whose result differed, and keep going."""
    return (f"        beqz    t3, 8f\n"
            f"        bnez    t5, 8f\n"
            f"        li      t5, {n}\n"
            f"8:")


# Lane inputs. Lanes 0 and 1 share an index deliberately.
LANE_IDX = [1, 1, 3, 0]
INT_INIT = [0x11, 0x22, 0x33, 0x44]        # memory before, per slot
INT_VALS = [0x0f, 0x30, 0x05, 0xf0]        # operand, per lane
FP_INIT = [1.0, 2.0, 3.0, 4.0]
FP_VALS = [0.5, -1.5, 2.25, -0.75]


def expected_int(op_fn, bits):
    """Apply the lanes in order, as the instruction does."""
    mem = list(INT_INIT)
    for lane in range(4):
        slot = LANE_IDX[lane]
        mem[slot] = op_fn(mem[slot], INT_VALS[lane], bits)
    return mem


def expected_fp(op_fn):
    mem = list(FP_INIT)
    for lane in range(4):
        slot = LANE_IDX[lane]
        mem[slot] = op_fn(mem[slot], FP_VALS[lane])
    return mem


emit("# GENERATED by sim/gen-tests.py -- do not edit.")
emit("#")
emit("# Every M²NDP instruction, run over four lanes and checked against")
emit("# values computed in Python rather than restated here by hand.")
emit("#")
emit("# t6 accumulates differences; the program exits 0 only if it stays zero,")
emit("# so any single instruction going wrong fails the run.")
emit()
emit("        .text")
emit("        .globl _start")
emit("_start:")
emit("        li      t0, (1 << 13) | (1 << 9)   # FS, VS = Initial")
emit("        csrs    mstatus, t0")
emit("        li      t5, 0                      # first failing test, 0 = none")
emit()

test_no = 0

# ---------------------------------------------------------------- vector int
for sew in (8, 16, 32, 64):
    store = {8: "sb", 16: "sh", 32: "sw", 64: "sd"}[sew]
    load = {8: "lbu", 16: "lhu", 32: "lwu", 64: "ld"}[sew]
    vle = {8: "vle8.v", 16: "vle16.v", 32: "vle32.v", 64: "vle64.v"}[sew]
    mask = (1 << sew) - 1

    for name, fn in INT_OPS:
        for iw in IDX_WIDTHS:
            test_no += 1
            want = expected_int(fn, sew)
            lbl = f"t{test_no}"
            emit(f"        # {name}ei{iw}.v  sew={sew}")
            emit(f"        la      a0, {lbl}_mem")
            emit(f"        la      a1, {lbl}_idx")
            emit(f"        la      a2, {lbl}_val")
            vlei = {8: "vle8.v", 16: "vle16.v", 32: "vle32.v",
                    64: "vle64.v"}[iw]
            emit(f"        vsetivli zero, {LANES}, e{iw}, m{lmul_for(iw)}, ta, ma")
            emit(f"        {vlei}  v{VIDX}, (a1)")
            emit(f"        vsetivli zero, {LANES}, e{sew}, m{lmul_for(sew)}, ta, ma")
            emit(f"        {vle}  v{VD}, (a2)")
            emit(f"        m2ndp.{name}ei{iw}.v v{VD}, (a0), v{VIDX}, v{VD}")
            emit("        li      t3, 0")
            for slot in range(4):
                emit(f"        {load}     t1, {slot * (sew // 8)}(a0)")
                emit(f"        li      t2, {want[slot] & mask}")
                emit(f"        xor     t1, t1, t2")
                emit(f"        or      t3, t3, t1")
            emit(record(test_no))
            emit()

# ----------------------------------------------------------------- vector fp
for sew, tobits, init, vals in (
    (32, f32_bits, FP_INIT, FP_VALS),
    (64, f64_bits, FP_INIT, FP_VALS),
):
    load = {32: "lwu", 64: "ld"}[sew]
    vle = {32: "vle32.v", 64: "vle64.v"}[sew]
    for name, fn in FP_OPS:
        for iw in IDX_WIDTHS:
            test_no += 1
            want = expected_fp(fn)
            lbl = f"t{test_no}"
            emit(f"        # {name}ei{iw}.v  sew={sew}")
            emit(f"        la      a0, {lbl}_mem")
            emit(f"        la      a1, {lbl}_idx")
            emit(f"        la      a2, {lbl}_val")
            vlei = {8: "vle8.v", 16: "vle16.v", 32: "vle32.v",
                    64: "vle64.v"}[iw]
            emit(f"        vsetivli zero, {LANES}, e{iw}, m{lmul_for(iw)}, ta, ma")
            emit(f"        {vlei}  v{VIDX}, (a1)")
            emit(f"        vsetivli zero, {LANES}, e{sew}, m{lmul_for(sew)}, ta, ma")
            emit(f"        {vle}  v{VD}, (a2)")
            emit(f"        m2ndp.{name}ei{iw}.v v{VD}, (a0), v{VIDX}, v{VD}")
            emit("        li      t3, 0")
            for slot in range(4):
                emit(f"        {load}     t1, {slot * (sew // 8)}(a0)")
                emit(f"        li      t2, {tobits(want[slot])}")
                emit(f"        xor     t1, t1, t2")
                emit(f"        or      t3, t3, t1")
            emit(record(test_no))
            emit()

# --------------------------------------------------------------- scalar fp
for width, tobits, ldi, fld, fsuffix in (
    (16, f16_bits, "lhu", "flh", "h"),
    (32, f32_bits, "lwu", "flw", "w"),
    (64, f64_bits, "ld", "fld", "d"),
):
    for name, fn in SCALAR_OPS:
        test_no += 1
        lbl = f"t{test_no}"
        old, operand = 3.5, -1.25
        want = fn(old, operand)
        emit(f"        # {name}.{fsuffix}")
        emit(f"        la      a0, {lbl}_mem")
        emit(f"        la      a1, {lbl}_val")
        emit(f"        {fld}    fa1, 0(a1)")
        emit(f"        m2ndp.{name}.{fsuffix} fa0, fa1, (a0)")
        emit("        li      t3, 0")
        emit(f"        {ldi}     t1, 0(a0)")
        emit(f"        li      t2, {tobits(want)}")
        emit(f"        xor     t1, t1, t2")
        emit(f"        or      t3, t3, t1")
        # The instruction also returns the previous value.
        emit(f"        fmv.x.{fsuffix} t1, fa0")
        emit(f"        li      t2, {tobits(old)}")
        emit(f"        xor     t1, t1, t2")
        emit(f"        or      t3, t3, t1")
        emit(record(test_no))
        emit()

emit("        # Exit code is the first test that disagreed, 0 if none did.")
emit("        mv      a0, t5")
emit("        slli    a0, a0, 1")
emit("        ori     a0, a0, 1")
emit("        la      t0, tohost")
emit("        sd      a0, 0(t0)")
emit("1:      j       1b")
emit()
emit("        .data")

# ------------------------------------------------------------------- data
test_no = 0
for sew in (8, 16, 32, 64):
    d = {8: ".byte", 16: ".half", 32: ".word", 64: ".dword"}[sew]
    for name, fn in INT_OPS:
        for iw in IDX_WIDTHS:
            test_no += 1
            di = {8: ".byte", 16: ".half", 32: ".word", 64: ".dword"}[iw]
            lbl = f"t{test_no}"
            emit("        .align 6")
            emit(f"{lbl}_idx:  {di} " +
                 ", ".join(str(i * (sew // 8)) for i in LANE_IDX))
            emit(f"        .align 6")
            emit(f"{lbl}_val:  {d} " + ", ".join(str(v) for v in INT_VALS))
            emit(f"        .align 6")
            emit(f"{lbl}_mem:  {d} " + ", ".join(str(v) for v in INT_INIT))

for sew, tobits in ((32, f32_bits), (64, f64_bits)):
    d = {32: ".word", 64: ".dword"}[sew]
    for name, fn in FP_OPS:
        for iw in IDX_WIDTHS:
            test_no += 1
            di = {8: ".byte", 16: ".half", 32: ".word", 64: ".dword"}[iw]
            lbl = f"t{test_no}"
            emit("        .align 6")
            emit(f"{lbl}_idx:  {di} " +
                 ", ".join(str(i * (sew // 8)) for i in LANE_IDX))
            emit(f"        .align 6")
            emit(f"{lbl}_val:  {d} " + ", ".join(str(tobits(v)) for v in FP_VALS))
            emit(f"        .align 6")
            emit(f"{lbl}_mem:  {d} " + ", ".join(str(tobits(v)) for v in FP_INIT))

for width, tobits in ((16, f16_bits), (32, f32_bits), (64, f64_bits)):
    d = {16: ".half", 32: ".word", 64: ".dword"}[width]
    for name, fn in SCALAR_OPS:
        test_no += 1
        lbl = f"t{test_no}"
        emit("        .align 6")
        emit(f"{lbl}_val:  {d} {tobits(-1.25)}")
        emit("        .align 6")
        emit(f"{lbl}_mem:  {d} {tobits(3.5)}")

emit()
emit('        .section .tohost,"aw",@progbits')
emit("        .align 6")
emit("        .globl tohost")
emit("tohost:   .dword 0")
emit("        .align 6")
emit("        .globl fromhost")
emit("fromhost: .dword 0")

sys.stdout.write("\n".join(out) + "\n")
